### PR TITLE
Add 2Miners payout address

### PR DESCRIPTION
**Pull request by slavikus**
Adding the 2Miners.com mining pool payout address that is used by the payouts system (miners can mine altcoins and automatically get paid in TON).

### CODE REVIEW

**Review by Dlibl — COMMENTED** [review]
address:UQA3J-OaFejIilFRP2VAn17S__mR3XNcVZmNbbt0ASTalzRh
name: 2Miners.com Mining Pool (TON Payouts)

**Review by Dlibl — APPROVED** [review]

**Review by Elgayar777 — APPROVED** [review]

**Review by Elgayar777 — COMMENTED** [review]
- [ ]

**Review by Elgayar777 — APPROVED** [review]

**Comment by Elgayar777** [comment]
Ok

**Review by Elgayar777 — COMMENTED** [review]
Okay

**Review by Elgayar777 — COMMENTED** [review]
UQDRfxpPznrGATdWXAzeQMdNHfz16nNhmiCmbz9dH3l-bZwK

**Pull request closed without merging**
